import {
  g1,
  g2,
  g3,
  g4,
  g5,
  g6,
  g7,
  g8,
  g9,
  g10,
  g11,
  g12,
  g13,
  g14,
  g15,
  g16,
} from "../../src/assets";

export const gallery = [
  { id: 1, title: "ТГЭУ 2024", date: new Date(), img: g1 },
  { id: 2, title: "ТГЭУ 2024", date: new Date(), img: g2 },
  { id: 3, title: "ТГЭУ 2024", date: new Date(), img: g3 },
  { id: 4, title: "ТГЭУ 2024", date: new Date(), img: g4 },
  { id: 5, title: "ТГЭУ 2024", date: new Date(), img: g5 },
  { id: 6, title: "ТГЭУ 2024", date: new Date(), img: g6 },
  { id: 7, title: "ТГЭУ 2024", date: new Date(), img: g7 },
  { id: 8, title: "ТГЭУ 2022", date: new Date(), img: g8 },
  { id: 9, title: "ТГЭУ 2022", date: new Date(), img: g9 },
  { id: 10, title: "Спорт 2021", date: new Date(), img: g10 },
  { id: 11, title: "Абдулла Каххар", date: new Date(), img: g11 },
  { id: 12, title: "Спектакль: Ромео и Джульетта", date: new Date(), img: g12 },
  {
    id: 13,
    title: "Конкурс: Одежда, которую носила моя бабушка",
    date: new Date(),
    img: g13,
  },
  { id: 14, title: "Конкурс: А ну-ка, девушки", date: new Date(), img: g14 },
  { id: 15, title: "КВН", date: new Date(), img: g15 },
  { id: 16, title: "День студента", date: new Date(), img: g16 },
];
